apiVersion: apps/v1
kind: Deployment
metadata:
  name: goot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goot
  template:
    metadata:
      labels:
        app: goot
    spec:
      containers:
      - image: okteto.dev/goot:latest
        name: goot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2a87a9f9-8b74-47d1-9133-2640c50f99ab"
        - name: Vless_Path
          value: "/2a87a9f9-8b74-47d1-9133-2640c50f99ab-vless"
        - name: Vmess_UUID
          value: "2a87a9f9-8b74-47d1-9133-2640c50f99ab"
        - name: Vmess_Path
          value: "/2a87a9f9-8b74-47d1-9133-2640c50f99ab-vmess"
        - name: Share_Path
          value: "/v2link"
